core/pom.xml, core/src/main/java/ma/glasnost/orika/converter/builtin/GuavaOptionalConverter.java, core/src/main/java/ma/glasnost/orika/impl/generator/VariableRef.java, pom.xml, tests/pom.xml, tests/src/main/java/ma/glasnost/orika/test/optional/GuavaOptionalTestCase.java
Note that Optional field mappings will need to make use of a converter (see the builtin GuavaOptionalConverter for details).
=> Add support for Java 8 & Guava Optional classes.

pom.xml
Javassist 3.19.0-GA adds Java 8 support
https://github.com/jboss-javassist/javassist/releases/tag/rel_3_19_0_ga
=> Update to use Javassist  3.19.0-GA

core/src/main/java/ma/glasnost/orika/metadata/TypeUtil.java, eclipse-tools/.settings/org.eclipse.jdt.core.prefs, eclipse-tools/.settings/org.eclipse.m2e.core.prefs, pom.xml, tests/src/main/java/ma/glasnost/orika/test/custommapper/CustomMappingTestCase.java
I will start with the first point of (MappingContext should only initialized and release one time per mapping graph)
https://groups.google.com/forum/#!topic/orika-discuss/C0j6zdYdZOg
But first:
* I remove the "/eclipse-tools/.settings" folder (I believe it was a mistake)
* Update JDK Version to 1.6 because the project dosn't compile with JDK 1.5:  
because Collections.newSetFromMap(...) in VariableRef.java [54] exists only since JDK 1.6
* fixed the bug created by fixing #69
thanks,
Harald
=> Orika 1.5.x - remove "/eclipse-tools/.settings"; update JDK version 1.6; Build Bugfix

core/src/main/java/ma/glasnost/orika/property/IntrospectorPropertyResolver.java, tests/src/main/java/ma/glasnost/orika/test/property/IntrospectorResolverTestCase.java
This pull request for issue #72 honours Java 7's @java.beans.Transient annotation and preserves backward compatibility to older Java versions at the same time.
=> Support for Transient annotation (issue #72)

.travis.yml, core/src/main/java/ma/glasnost/orika/metadata/TypeFactory.java, tests/src/main/java/ma/glasnost/orika/test/custommapper/CustomMappingTestCase.java, tests/src/main/java/ma/glasnost/orika/test/inheritance/UsedMappersTestCase.java, tests/src/main/java/ma/glasnost/orika/test/metadata/TypeFactoryTestCase.java, tests/src/main/java/ma/glasnost/orika/test/perf/ClassLoaderLeakageTestCase.java, tests/src/main/java/ma/glasnost/orika/test/perf/MultiThreadedTestCase.java
added JDK6 to travis-ci and fix a UnitTest which failed in JDK6.
The UnitTest didn't validate that the exclude "really" worked.
In openJDK6 it didn't worked because the Stacktrace could not be copied from one instance to another..
But the exclution did also not work in other JDKs. But the Test didn't fail because the StackTrace could be copied in other JDKs without error.
I added a TODO into the Test. Maybe there is a real problem!?
BTW: do you know why GitHub cannot create a nice Diff?
with friendly regards,
Harald
ps.: at next I will look at the ConcurrentModificationException that occurs sometimes in TypeFactory.refineBounds(311)
=> Orika 1.5.x

.travis.yml, pom.xml, tests-jdk8/.gitignore, tests-jdk8/pom.xml, tests-jdk8/src/test/java/ma/glasnost/orika/test/jdk8/InterfaceDefaultMethodTest.java
Hi,
I created an additional sub-module for special JDK-8 Tests for analysing the question:
https://groups.google.com/forum/#!topic/orika-discuss/0l1_LPNW-6A
This Sub-modules runs on Travis-ci only for the JDK-8 build.
I'm not sure if you like it. At the moment there is only one test in it..
Please let me know.
=> Add Sub-Module for special jdk8 tests

core/src/main/java/ma/glasnost/orika/impl/generator/MultiOccurrenceVariableRef.java, core/src/main/java/ma/glasnost/orika/impl/generator/specification/MultiOccurrenceToMultiOccurrence.java, tests/src/main/java/ma/glasnost/orika/test/community/PullRequest88TestCase.java
This pull request fixes #82.
It makes the generated mapper preserve the values of a target map, when mapping from a MultiOccurenceVariable to a MultiOccurenceVariable.
=> Do not loose Map instance when mapping MultiOccurenceVariable to a Map

core/src/main/java/ma/glasnost/orika/converter/builtin/CloneableConverter.java, tests/src/main/java/ma/glasnost/orika/test/converter/CloneableConverterTestCase.java
Hi,
I'm using Orika to map JAXWS generated code to JAXRS generated a code. I found an issue with the CloneableConverter that causes a NullPointerException if the source object is null. Strangely enough, the issue only seems to happen when using a somewhat object complex structure.
I added a unit test to CloneableConverterTestCase to demonstrate the issue, which was trivial to fix.
=> Fix for NullPointerException in CloneableConverter

pom.xml
Fix for  https://github.com/orika-mapper/orika/issues/60 Updated paranamer version has fix for lambda expressions
=> update paranamer to version 2.8

core/src/main/java/ma/glasnost/orika/property/PropertyResolver.java, tests/src/main/java/ma/glasnost/orika/test/community/issue131/Issue131Test.java, tests/src/main/java/ma/glasnost/orika/test/property/PropertyResolverTestCase.java
Previously property types with generics were resolved
only from classes in inheritance hierarchy.
With this change support is added for generics like
```
interface B<T> {
T getProperty();
void setProperty(T property);
Collection<T> getContent();
void setContent(Collection<T> content);
}
abstract class A implements B<T> {
}
```
Fix #131
=> Support property types from generic interfaces.

core/src/main/java/ma/glasnost/orika/impl/generator/ObjectFactoryGenerator.java
I am hoping such a minor fix does not need a full test.  I will write one up if needed.
When attempting to automap incompatible classes, this line generates a null pointer exception instead of the much more helpful mapping exception that is intended.
ParameterTypes are never set in [SimpleConstructorResolverFactory](https://github.com/orika-mapper/orika/blob/master/core/src/main/java/ma/glasnost/orika/constructor/SimpleConstructorResolverStrategy.java#L138) when targetParameters and parameterNames (line 128) do not match up.
As a result, this exception, I assume is intended, for this situation is never thrown.
=> Catch case where constructorArguments are not set

core/src/main/java/ma/glasnost/orika/impl/DefaultCodeGenerationStrategy.java, core/src/main/java/ma/glasnost/orika/impl/generator/AggregateSpecification.java, core/src/main/java/ma/glasnost/orika/impl/generator/BaseSpecification.java, core/src/main/java/ma/glasnost/orika/impl/generator/CodeGenerationStrategy.java, core/src/main/java/ma/glasnost/orika/impl/generator/Specification.java, tests/src/main/java/ma/glasnost/orika/test/generator/CodeGenerationAddSpecificationCase.java
Please see the issue for description: https://github.com/orika-mapper/orika/issues/134
I had to do some refactoring (create a base interface for Specification and AggregateSpecification) to make DefaultCodeGenerationStrategy.addSpec() work with the change to CodeGenerationStrategy.
=> Fix for issue#134

core/src/main/java/ma/glasnost/orika/property/RegexPropertyResolver.java, tests/src/main/java/ma/glasnost/orika/test/property/RegexPropertyResolverTestCase.java, tests/src/main/java/ma/glasnost/orika/test/property/TestCaseClasses.java
Currently you cannot use a regex that has more than one capture group
because the RegexPropertyResolver assumes group(1) is the capture group
that will specify the property name.
In my code base I have the following use case:
1.  Some classes in the code base are immutable and you construct them
using a Builder class.
2. Some of the builder classes use a withXXX convention
3. Some of the builder classes use a setXXX convention
4. I needed a write method regex of “(with|set)(\\w+)” which broke when
the RegexPropertyResolver expected the group containing the property
name to have be index 1.
This change should be backwards compatible.
=> Enhance RegexPropertyResolver to allow regex expressions with more than one capture group

core/src/main/java/ma/glasnost/orika/impl/DefaultMapperFactory.java, tests/src/main/java/ma/glasnost/orika/test/objectfactory/CustomFactory.java, tests/src/main/java/ma/glasnost/orika/test/objectfactory/MultipleObjectFactoryTest.java
#176 causes a regression in the way ObjectFactories are selected. Given a type hierarchy with Base and Sub1 and Sub2, both extending Base, a factory for Sub1 or Sub2 might be returned when looking up a factory for Base. When a perfect match exists, it should always prefer that factory.
This PR fixes the issue and adds a testcase demonstrating the problem.
=> Fix objectfactory selection

core/src/main/java/ma/glasnost/orika/impl/MapperFacadeImpl.java, tests/src/main/java/ma/glasnost/orika/test/unenhance/inheritance/HibernateProxyTestCase.java
This patch fixes mapAsList to correctly resolve the types of the elements in the collection using the unenhance strategy. I'm not sure if the use of getClass(source) is correct (which uses userUnenhanceStrategy), or if unenhanceStrategy should be used. The change does fix the added testcase.
=> Fix mapAsList with list of proxies with different types

core/src/main/java/ma/glasnost/orika/constructor/PrefixParamConstructorResolverStrategy.java, core/src/main/java/ma/glasnost/orika/constructor/SimpleConstructorResolverStrategy.java, core/src/main/java/ma/glasnost/orika/impl/util/StringUtil.java, pom.xml, tests/src/main/java/DefaultPackageTestCase.java, tests/src/main/java/ma/glasnost/orika/test/constructor/ConstructorMappingTestCase.java, tests/src/main/java/ma/glasnost/orika/test/constructor/TestCaseClasses.java, tests/src/main/java/ma/glasnost/orika/test/util/StringUtilTest.java
It's extended to handle constructor param names that follow a prefix-letter naming convention. For instance p-prefixed param names - (pName, pAge).
=> Add an extension point to simple constructor resolver strategy

.travis.yml, core/src/main/java/ma/glasnost/orika/converter/builtin/DateAndTimeConverters.java, tests/src/main/java/ma/glasnost/orika/test/BrokenTest.java
When checking assignments for XMLGregorian calendar, it checks if Object is assignableFrom things like XMLGregorianCalendar, which is true.  Since everything ultimately inherits from Object, this causes GregorianCalendar to match XMLGregorianCalendar, causing a cast issue.
Fixes #212
=> Date and Time objects to Object fix

.travis.yml, core/pom.xml, pom.xml, tests-jdk8/pom.xml, tests-jdk8/src/test/java/ma/glasnost/orika/test/jdk8/JavaDateApiTest.java, tests/pom.xml, tests/src/main/java/ma/glasnost/orika/test/boundmapperfacade/GenericCollectionsTestCase.java, tests/src/main/java/ma/glasnost/orika/test/common/types/TestCaseClasses.java, tests/src/main/java/ma/glasnost/orika/test/community/Issue175Test.java, tests/src/main/java/ma/glasnost/orika/test/community/Issue176WithSuperClassesTestCase.java, tests/src/main/java/ma/glasnost/orika/test/community/issue121/util/RandomUtils.java, tests/src/main/java/ma/glasnost/orika/test/constructor/TestCaseClasses.java, tests/src/main/java/ma/glasnost/orika/test/converter/CloneableConverterNoSetAccessibleTestCase.java, tests/src/main/java/ma/glasnost/orika/test/converter/CloneableConverterTestCase.java, tests/src/main/java/ma/glasnost/orika/test/converter/PassThroughConverterTestCase.java, tests/src/main/java/ma/glasnost/orika/test/extensibility/MappingContextFactoryExtensibilityTestCase.java, tests/src/main/java/ma/glasnost/orika/test/generator/ExpanderTestCase.java, tests/src/main/java/ma/glasnost/orika/test/generator/TestCompilerStrategyWritingFiles.java, tests/src/main/java/ma/glasnost/orika/test/generics/GenericCollectionsTestCase.java, tests/src/main/java/ma/glasnost/orika/test/perf/MultiThreadedTestCase.java, tests/src/main/java/ma/glasnost/orika/test/unenhance/HibernateProxyTestCase.java, tests/src/main/resources/HibernateProxyTestCase-context.xml, tests/src/main/resources/Issue20TestCase-context.xml, tests/src/main/resources/Issue21TestCase-context.xml
This is my attempt on updating some of the dependencies so orika is able to run on java 9.
After these changes orika can be build on java 7,8 and 9 😄 
see https://travis-ci.org/123Haynes/orika for confirmation.
@elaatifi can you please take a look when you have some time? 😃 
closes https://github.com/orika-mapper/orika/issues/141, https://github.com/orika-mapper/orika/issues/242
=> Update dependencies to support java 9

.travis.yml, core/pom.xml, pom.xml
Java 7 has reached its EOL since 2015.
Since keeping this old compability prevents orika
from using some newer libraries, let's remove support for it.  
No one in their right mind should use this old java version in actively maintained production environments where new versions of orika might be useful.
=> Remove Java 7 Builds

pom.xml, tests/src/main/java/ma/glasnost/orika/test/DynamicSuite.java
update javassist to 3.23.1-GA
update easymock to 3.6
add required cast needed for javassist update
=>  bump version for javassist and easymock 

pom.xml, tests-jdk8/pom.xml, tests-jdk8/src/test/java/ma/glasnost/orika/test/jdk8/JavaDateApiTest.java
- Make sure java8 tests run on any jdk >= 8
- Remove duplicated javassist.version property defined in orika-tests-jdk8 pom file
- Use fast-classpath-scanner library for finding subclasses - this library understands Java 9 modules
=> Make sure java8 tests run on any jdk >= 8

core/pom.xml, eclipse-tools/pom.xml, pom.xml, tests-jdk8/pom.xml, tests/pom.xml
- Add pluginManagement section to control plugin versions
- Updated plugin versions
- Remove redundant maven-compiler-plugin entry in tests-jdk8. Java 8 source/target already setup in parent pom
=> Add pluginManagement section to parent

README.md, core/pom.xml, core/src/test/java/ma/glasnost/orika/test/community/Issue160TestCase.java, core/src/test/java/ma/glasnost/orika/test/community/Issue166TestCase.java, core/src/test/java/ma/glasnost/orika/test/community/Issue167TestCase.java, pom.xml
This PR merges the changes from the master branch and fixes a few errors related to the hamcrest update.
Junit 4.12 still uses hamcrest 1.3, so I updated Junit to Junit 5 and excluded hamcrest there.
Please note that the Test for Issue 46 always fails locally for me. I'm not sure if this is because of my setup or if there really is an error.
the trace is:
```
java.lang.AssertionError: Failed to process graph. failed after 7 transforms, exception = ma.glasnost.orika.MappingException: While attempting the following mapping:
sourceClass = class ma.glasnost.orika.test.community.Issue46TestCase$Two
sourceType = ma.glasnost.orika.test.community.Issue46TestCase.Two
destinationType = ma.glasnost.orika.test.community.Issue46TestCase.Two
resolvedStrategy = InstantiateAndUseCustomMapperStrategy<Two, …
```
=> Merge changes from master

eclipse-tools/pom.xml, tests/pom.xml
Also, the transitive dependency `org.eclipse.core.commands` in module `orika-eclipse-tools` can be excluded, since it is not used.
=> Remove unused dependencies

core/src/main/java/ma/glasnost/orika/metadata/TypeFactory.java
This PR fixes a NPE that happens if a WeakReference for Type is GC'd.
=> Fix NPE if weak reference is GCd

core/src/main/java/ma/glasnost/orika/impl/DefaultBoundMapperFacade.java, tests/src/main/java/ma/glasnost/orika/test/concurrency/DefaultBoundMapperFacadeConcurrentInitTestCase.java, tests/src/main/java/ma/glasnost/orika/test/concurrency/model/ModelWithNestedObjDest.java, tests/src/main/java/ma/glasnost/orika/test/concurrency/model/ModelWithNestedObjSource.java, tests/src/main/java/ma/glasnost/orika/test/concurrency/model/NestedModel.java
When several concurrent threads are trying to set `defaultStrategy` in `BoundStrategyCache` one of the threads may end up with wrong strategy. In that case the mapper will throw exception which will look something like this:
```
Caused by: ma.glasnost.orika.MappingException: While attempting the following mapping:
sourceClass = class ma.glasnost.orika.test.concurrency.model.NestedModel
sourceType = ma.glasnost.orika.test.concurrency.model.NestedModel
destinationType = ma.glasnost.orika.test.concurrency.model.NestedModel
resolvedStrategy = InstantiateAndUseCustomMapperStrategy<NestedModel, NestedModel> {customMapper: GeneratedMapper<NestedModel, NestedModel> {usedConverters: [], usedMappers: [], usedMapperFacades: [DefaultBoundMapperFacade<Object, Object>], usedTypes: [] }, unenhancer: …
```
=> BoundStrategyCache race condition fix

core/src/main/java/ma/glasnost/orika/impl/MapperFacadeImpl.java
Since the size of destination collection is equal (or possibly a bit lower in *mapAsSet* and *mapAsMap* methods) to the number of elements of source iterable, the initial capacity of the destination collection can most of the times be specified on its creation.
Therefore in case the source iterable is subtype of *java.util.Collection*, its size is retrieved and used to specify initial capacity of destination collection. Otherwise destination collection is instantiated with default initial capacity as for iterables which are not subtype of *java.util.Collection* it is required iterating through each their element in order to get their amount.
**Benchmarking**
scenario: transforming iterable of 2,500,000 elements into corresponding DTO objects using Orika's mapAsList method
* only …
=> Add minor performance improvements on methods using mapAsCollection

pom.xml
Would you please consider to release a new version which have this PR include?
=> Remove java-sizeof as it's end of life

core/src/test/java/ma/glasnost/orika/test/generator/BeanToArrayGenerationTestCase.java
POINT OF FAILURE -> random attribute ordering produced by factory.classMap(Clazz, Clazz) **When field(*fromClassField*, *toClassField*) is not called for all hierarchical attributes, the one left out will appear in random order.**
Example:
``` 
{
"a" : 1,
"b" : {
"c": 2,
"d": 3
}
}
```
and when --""--.field("b.c", "0") is called, (converting obj to Object[ ])
the mapped destination Object[ ] could be: [2, 1, 3] OR [2, 3, 1]
***
Possible fix: for all unmapped attrs, use lexographical ordering or throw exception
Fixed using NonDex, plugin added in parent pom.
Suggested command to check flaky tests :
> mvn nondex:nondex
For particular test:
Add the following lines to your pom.xml
```
<plugin> 
<groupId>edu.illinois</groupId>
<artifactId>nondex-maven-plugin</artifactId> …
```
=> Fixed flaky test-case in the class (orika/core): BeanToArrayGenerationTestCase.testBeanToArrayGeneration
