orika-mapper/orika

- core/src/main/java/ma/glasnost/orika/impl/generator/SourceCodeContext.java
- core/src/main/java/ma/glasnost/orika/impl/generator/VariableRef.java
- tests/src/main/java/ma/glasnost/orika/test/filters/NestedPropertyFilterTest.java
Nested Property causes NullPointerException in dest argument of
shouldMap method.
> Fix for bug #189 https://code.google.com/p/orika/issues/detail?id=189

- .travis.yml
- tests/pom.xml
fix travis-ci-build: update surefire-plugin.
> Orika 1.5.x

- core/src/main/java/ma/glasnost/orika/metadata/TypeUtil.java
- tests/src/main/java/ma/glasnost/orika/test/property/PropertyResolverTestCase.java
This pull request fix Issue [#83](https://github.com/orika-mapper/orika/issues/83)
> Parameterized type

- core/src/main/java/ma/glasnost/orika/impl/MapperFacadeImpl.java
In my case the map is in place and the destination type
is an interface so the flow goes into the if clause and
resolvedDestinationType to the interface.
> Avoid check if map is in place.

- core/src/main/java/ma/glasnost/orika/impl/generator/JavassistCompilerStrategy.java
> ClassLoader Coherency

- core/src/main/java/ma/glasnost/orika/impl/DefaultMapperFactory.java
The build was broken because the wrong parameter was passed to resolveValueOf in resolveConcreteType method.
I fixed it and I extracted a method too, to avoid duplication.
> Fix #125 travis build

- core/src/main/java/ma/glasnost/orika/metadata/Type.java
- tests/src/main/java/ma/glasnost/orika/test/community/issue148/Issue148Test.java
> Type#isAssignable now checks interfaces too

- core/src/main/java/ma/glasnost/orika/impl/generator/MapperGenerator.java
- core/src/main/java/ma/glasnost/orika/impl/generator/ObjectFactoryGenerator.java
- core/src/main/java/ma/glasnost/orika/impl/generator/SourceCodeContext.java
- core/src/main/java/ma/glasnost/orika/impl/generator/specification/Convert.java
- core/src/main/java/ma/glasnost/orika/impl/generator/specification/MapToMap.java
- core/src/main/java/ma/glasnost/orika/impl/generator/specification/MultiOccurrenceToMultiOccurrence.java
- tests/src/main/java/ma/glasnost/orika/test/community/Issue64Test.java
I fixed issue #64 by adding a verification of container's null value in case of multi occurrence to multi occurrence field mapping.
I cleaned a bit the MultiOccurrenceToMultiOccurrence class.
> Fix Issue #64

- core/src/main/java/ma/glasnost/orika/impl/DefaultMapperFactory.java
Setted that flag at false by default, as discussion on  #106
> Set DUMP_STATE_ON_EXCEPTION default at false

- core/src/main/java/ma/glasnost/orika/impl/DefaultConcreteTypeMap.java
- core/src/main/java/ma/glasnost/orika/impl/DefaultMapperFactory.java
- core/src/main/java/ma/glasnost/orika/impl/generator/MultiOccurrenceVariableRef.java
As discussion in #58 , extracted the knowledge of concrete type map to a common class and used it into MultiOccurrenceVariableRef#newInstance
> Refactor MultiOccurrenceVariableRef#newInstance

- pom.xml
> Upgrade CuncurrentLinkedHasMap to 1.4.2

- core/src/main/java/ma/glasnost/orika/constructor/ConstructorParameterResolver.java
- core/src/main/java/ma/glasnost/orika/converter/builtin/ConstructorConverter.java
- core/src/main/java/ma/glasnost/orika/converter/builtin/CopyByReferenceConverter.java
- core/src/main/java/ma/glasnost/orika/impl/DefaultMapperFactory.java
- core/src/main/java/ma/glasnost/orika/impl/MapperFacadeImpl.java
- core/src/main/java/ma/glasnost/orika/impl/Specifications.java
- core/src/main/java/ma/glasnost/orika/impl/generator/MapperGenerator.java
- core/src/main/java/ma/glasnost/orika/impl/generator/MultiOccurrenceVariableRef.java
- core/src/main/java/ma/glasnost/orika/impl/generator/SourceCodeContext.java
- core/src/main/java/ma/glasnost/orika/impl/generator/specification/CopyByReference.java
- core/src/main/java/ma/glasnost/orika/impl/generator/specification/MultiOccurrenceToMultiOccurrence.java
- core/src/main/java/ma/glasnost/orika/impl/util/ClassUtil.java
- core/src/main/java/ma/glasnost/orika/metadata/ClassMapBuilder.java
- core/src/main/java/ma/glasnost/orika/metadata/Type.java
- tests/src/main/java/ma/glasnost/orika/test/community/Issue91Test.java
Fix issue #91 and done some refactors
> Fix #91 and refactor

- core/src/main/java/ma/glasnost/orika/CustomConverter.java
- core/src/main/java/ma/glasnost/orika/util/ClassHelper.java
- tests/pom.xml
- tests/src/main/java/ma/glasnost/orika/test/community/Issue129TestCase.java
- tests/src/main/java/ma/glasnost/orika/test/util/ClassHelperTest.java
- tests/src/main/java/ma/glasnost/orika/test/util/GenericInterface.java
please look at the comment in customconverter constructor
> pr-issue129

- core/src/main/java/ma/glasnost/orika/metadata/TypeFactory.java
- core/src/main/java/ma/glasnost/orika/property/PropertyResolver.java
- tests/src/main/java/ma/glasnost/orika/test/community/Issue166TestCase.java
- tests/src/main/java/ma/glasnost/orika/test/community/Issue167TestCase.java
Break recursions like "class Enum<E extends Enum<E>>"
> fix #166 StackOverflowError exception when mapping enum.

- core/src/main/java/ma/glasnost/orika/impl/DefaultMapperFactory.java
- core/src/main/java/ma/glasnost/orika/impl/MultipleMapperWrapper.java
- core/src/main/java/ma/glasnost/orika/metadata/TypeUtil.java
- tests/src/main/java/ma/glasnost/orika/test/TestUtil.java
- tests/src/main/java/ma/glasnost/orika/test/community/Issue176TestCase.java
- tests/src/main/java/ma/glasnost/orika/test/community/Issue176WithInterfacesTestCase.java
- tests/src/main/java/ma/glasnost/orika/test/community/Issue176WithSuperClassesTestCase.java
- tests/src/main/java/ma/glasnost/orika/test/community/Issue188TestCase.java
- tests/src/main/java/ma/glasnost/orika/test/community/issue131/Issue131Test.java
- tests/src/main/java/ma/glasnost/orika/test/map/MultipleMapperWrapperTest.java
- tests/src/main/java/ma/glasnost/orika/test/map/MultipleMapperWrapperTestSuite.java
> Implement Support for mapping one type to many #176 And Fix for #188

- core/src/main/java/ma/glasnost/orika/converter/builtin/BuiltinConverters.java
- core/src/main/java/ma/glasnost/orika/metadata/Type.java
- tests/src/main/java/ma/glasnost/orika/test/converter/ConstructorConverterTestCase.java
#193 Exception mapping java.util.Currency
#194 Built-In Constructor Converter get lost from Version 1.4.6 to 1.5
> Fixes for #193 and #194

- core/src/main/java/ma/glasnost/orika/CustomFilter.java
- tests/src/main/java/ma/glasnost/orika/test/community/Issue232Test.java
Just added a null pointer guard to avoid null pointer exception ;)
> Add null pointer guard to fix #232

- core/src/main/java/ma/glasnost/orika/MapEntry.java
- core/src/main/java/ma/glasnost/orika/property/PropertyResolver.java
- tests/src/main/java/ma/glasnost/orika/test/generator/BeanToMapGenerationTestCase.java
Hi, great library thanks! I found a couple of problems trying to reference values out of multiply-nested maps as fields on DTOs generated from swagger schemas - tests and fixes here if you want them.
> Multiply-Nested Maps

- .travis.yml
> Add jdk11 build

- core/src/main/java/ma/glasnost/orika/metadata/TypeUtil.java
- tests/src/main/java/ma/glasnost/orika/test/metadata/Issues296Test.java
> fix #296 issues

- core/src/main/java/ma/glasnost/orika/impl/generator/JavassistCompilerStrategy.java
- Log where source file is written to
- Fix spelling "occured" -> "occurred"
> Log where source file is written to

- core/src/main/java/ma/glasnost/orika/impl/generator/specification/Convert.java
- tests/src/main/java/ma/glasnost/orika/test/community/Issue322TestCase.java
> Fix issue 322

- core/src/main/java/ma/glasnost/orika/impl/generator/JavassistCompilerStrategy.java
Hit this error today and spellcheck caught the missing letter!
> Just fixing a typo
